/*****************************************
	N£meros de versiones para
	cada parte del sistema SINTAC.
*****************************************/

/* mensaje de aviso de la versi¢n de dominio p£blico */
#define DOMINIO_PUB "\n\nATENCION: Este programa es de dominio p£blico,\n\
y como tal debe ser distribuido GRATUITAMENTE.\n\n"

#define VERSION_CS  "T2.00"     /* versi¢n compilador */

#define VERSION_IS  "T1.33"     /* versi¢n int‚rprete-debugger */

#define VERSION_LS  "T1.50"     /* versi¢n listador */
