/***************************************************/
/* N£meros de versiones para cada parte del SINTAC */
/***************************************************/

#define VERSION_CSR "T1.00R\n\n"        /* versi¢n compilador reducido */
#define VERSION_CS  "T1.00\n\n"         /* versi¢n compilador */
#define VERSION_IS  "T1.00\n\n"         /* versi¢n int‚rprete-debugger */
#define VERSION_LS  "T1.00\n\n"         /* versi¢n listador */
