/***************************************
	Fichero de cabecera con las
	definiciones de colores.
***************************************/

/* men£s de opciones */
#define COLOR_MEN       0x70    /* color principal */
#define COLOR_MENS1     0x7f    /*   "   sombra 1 */
#define COLOR_MENS2     0x70    /*   "   sombra 2 */
#define COLOR_MENTEC    0x74    /*   "   teclas activaci¢n */
#define COLOR_MENSEL    0x07    /*   "   opci¢n seleccionada */

/* ventana de edici¢n */
#define COLOR_VED       0x07    /* color principal */
#define COLOR_VEDS1     0x0f    /*   "   sombra 1 */
#define COLOR_VEDS2     0x07    /*   "   sombra 2 */
#define COLOR_VEDBLQ    0x70    /*   "   bloque */

/* cuadros de di logo */
#define COLOR_DLG       0x70    /* color principal */
#define COLOR_DLGS1     0x7f    /*   "   sombra 1  */
#define COLOR_DLGS2     0x70    /*   "   sombra 2  */
#define COLOR_DLGTEC    0x74    /*   "   teclas activaci¢n */
#define COLOR_DLGSEL    0x07    /*   "   elemento seleccionado */

/* ventana de ayuda */
#define COLOR_AYD       0x30    /* color principal */
#define COLOR_AYDS1     0x3b    /*   "   sombra 1  */
#define COLOR_AYDS2     0x31    /*   "   sombra 2  */
#define COLOR_AYDTEC    0x39    /*   "   teclas activaci¢n */
#define COLOR_AYDSEL    0x03    /*   "   elemento seleccionado */

/* ventana de errores */
#define COLOR_ERR       0x4f    /* color principal */
#define COLOR_ERRS1     0x4c    /*   "   sombra 1  */
#define COLOR_ERRS2     0x40    /*   "   sombra 2  */
#define COLOR_ERRTEC    0x4e    /*   "   teclas activaci¢n */
#define COLOR_ERRSEL    0x0f    /*   "   elemento seleccionado */

/* ventana de compilador */
#define COLOR_CS        0x70    /* color principal */
#define COLOR_CSS1      0x7f    /*   "   sombra 1  */
#define COLOR_CSS2      0x70    /*   "   sombra 2  */
#define COLOR_CSTEC     0x74    /*   "   teclas activaci¢n */
#define COLOR_CSSEL     0x07    /*   "   elemento seleccionado */
