/***************************************************/
/* N£meros de versiones para cada parte del SINTAC */
/***************************************************/

#define DOMINIO_PUB "\n\nATENCION: Este programa es de dominio p£blico,\n\
y como tal debe ser distribuido GRATUITAMENTE.\n\n"
#define VERSION_CS  "T1.11"DOMINIO_PUB  /* versi¢n compilador */
#define VERSION_IS  "T1.33"             /* versi¢n int‚rprete-debugger */
#define VERSION_LS  "T1.00"DOMINIO_PUB  /* versi¢n listador */
