/*****************************************
	Fichero de cabecera con las
	definiciones de colores.
*****************************************/

#define COLOR_SCR    0x07       /* color general de pantalla */
#define COLOR_EDIT   0x07       /* color de zona de edici¢n */
#define COLOR_REGLA  0x70       /* color de la regleta */
#define COLOR_CAB    0x3f       /* color de cabecera */
#define COLOR_LINST  0x30       /* color de la l¡nea de estado */
#define COLOR_MENU   0x70       /* color del men£ de opciones */
#define COLOR_TECLA  0x74       /* color de tecla de activaci¢n */
#define COLOR_OPC    0x07       /* color opci¢n resaltada */
#define COLOR_WCOMP  0x70       /* color de ventana de compilador */
#define COLOR_WERR   0x1f       /* color de ventana de errores */
#define COLOR_ERR    0x4f       /* color ventana errores entorno */
#define COLOR_ERRSEL 0x74       /* color de error resaltado */
#define COLOR_AY     0x70       /* color de ventana de ayuda */
#define COLOR_APTDO  0x74       /* color de cabecera de apartado */
#define COLOR_REF    0x71       /* color de referencia de ayuda */
