/*****************************************
	N£meros de versiones para
	cada parte del sistema SINTAC
	y mensajes de copyright.
*****************************************/

#if !defined (VERSION_H)
#define VERSION_H

#define COPYRIGHT   "S.I.N.T.A.C. (c)1993 JSJ Soft Ltd."

#define VERSION_CS  "G1.00"     /* versi¢n compilador */

#define VERSION_IS  "G1.00"     /* versi¢n int‚rprete-debugger */

#define VERSION_LS  "G1.00"     /* versi¢n listador */

#define VERSION_EDS "G1.00"     /* versi¢n entorno de programaci¢n */

#endif  /* VERSION_H */
